name: Build Image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: hugodelahousse
        password: ${{ secrets.GITHUB_TOKEN }}
        repository: website-identity/website-identity
        registry: docker.pkg.github.com/hugodelahousse
        tags: latest
